# Generated by Django 6.1.1 on 2026-09-15 00:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, help_text='Add the latest information for the OHDSI Australia community.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short statement shown below the homepage title.'),
        ),
    ]
