# Generated by Django 6.1.1 on 2026-09-30 01:55

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='explorer_title',
            field=models.CharField(blank=True, help_text='Optional pathway label. Leave blank to use the page title.', max_length=200),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Include this page on the general overview map.'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='koa_pose',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('open', 'Explain'), ('wave', 'Connect'), ('excited', 'Celebrate')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='koa_tip',
            field=models.TextField(blank=True, help_text='Editorial guidance Koa shows when this page is opened.'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='legacy_pathway_key',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='pathway_priority',
            field=models.PositiveIntegerField(default=50, help_text='Lower numbers appear earlier when relevance is equal.'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='related_pages',
            field=wagtail.fields.StreamField([('page', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.ContentPage']})}, default=list),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='topics',
            field=models.TextField(blank=True, help_text='Search terms and synonyms, separated by commas. Used to match visitor questions.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='empty_content_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='goal_examples',
            field=wagtail.fields.StreamField([('question', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'max_length': 400}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('question', 1)]], {})}, default=list),
        ),
        migrations.AddField(
            model_name='homepage',
            name='goal_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='goal_placeholder',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='homepage',
            name='journey_hint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='koa_fallback_tip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='perspectives',
            field=wagtail.fields.StreamField([('perspective', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Stable identifier, for example researcher. Use letters, digits and hyphens.'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text on the perspective selection button.'}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Words that describe this audience, separated by commas.', 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.ContentPage']}), 6: ('wagtail.blocks.ListBlock', (5,), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('key', 0), ('label', 1), ('title', 2), ('description', 3), ('guide_message', 3), ('keywords', 4), ('starting_pages', 6)]], {})}, default=list),
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcome_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Content retrieved into the explorer and used by Koa.'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='intro',
            field=models.TextField(blank=True, help_text='Summary shown in cards and the content view.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
