# Generated by Django 6.1.1 on 2026-09-30 02:09

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_seed_managed_explorer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='perspectives',
            field=wagtail.fields.StreamField([('perspective', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Stable identifier, for example researcher. Use letters, digits and hyphens.', 'max_length': 40, 'validators': [django.core.validators.RegexValidator('^[a-z][a-z0-9-]{0,39}$', 'Start with a lowercase letter; use lowercase letters, digits and hyphens.')]}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text on the perspective selection button.'}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Words that describe this audience, separated by commas.', 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.ContentPage']}), 6: ('wagtail.blocks.ListBlock', (5,), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('key', 0), ('label', 1), ('title', 2), ('description', 3), ('guide_message', 3), ('keywords', 4), ('starting_pages', 6)]], {})}, default=list),
        ),
    ]
